#!/bin/bash

HF_token=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


curl -X GET -H "Authorization: Bearer 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" "https://datasets-server.huggingface.co/rows?dataset=GaussianWorld%2Fscene_splat_7k&config=3RScanGS&split=train&offset=0&length=100"

hf download GaussianWorld/scannet_mini_val_set_suite --repo-type=dataset --local-dir ./scannet_mini_val



hf download GaussianWorld/matterport3d_region_mcmc_3dgs_preprocessed --local-dir /mnt/Data3/liyan/matterport --repo-type dataset